var car = 'subaru';
console.log("Is car == 'subaru'? I predict true.");
console.log(car == 'subaru');
console.log("Is car == 'honda'? I predict false.");
console.log(car == 'honda');
console.log("Is car === 'subaru'? I predict true.");
console.log(car === 'subaru');
console.log("Is car === 'Subaru'? I predict false.");
console.log(car === 'Subaru');
console.log("Is car != 'ford'? I predict true.");
console.log(car != 'ford');
console.log("Is car != 'subaru'? I predict false.");
console.log(car != 'subaru');
console.log("Is car !== 'subaru'? I predict false.");
console.log(car !== 'subaru');
console.log("Is car !== 'Subaru'? I predict true.");
console.log(car !== 'Subaru');
console.log("Is car < 'volvo'? I predict true.");
console.log(car < 'volvo');
console.log("Is car > 'audi'? I predict false.");
console.log(car > 'audi');
